# Generated by Django 4.2.30 on 2026-05-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_projectmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
