# Generated by Django 4.2.30 on 2026-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
