# Generated by Django 4.2.30 on 2026-05-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_reminder_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
