# Generated by Django 4.2.30 on 2026-05-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_deleted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="reminder_sent",
            new_name="overdue_reminder_sent",
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_1h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
    ]
