# Generated by Django 4.2.30 on 2026-05-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_projectmember_role"),
        ("tasks", "0007_task_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["creator", "status"], name="tasks_task_creator_914dac_idx"
            ),
        ),
    ]
