# Generated by Django 4.2.30 on 2026-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
