# Build stage
FROM node:20-alpine as build-stage

WORKDIR /app

COPY frontend/Dgekichan/package*.json ./
RUN npm install

COPY frontend/Dgekichan/ ./
RUN npm run build

# Production stage
FROM alpine:latest
COPY --from=build-stage /app/dist /dist
CMD ["cp", "-rv", "/dist/.", "/output/"]
