# Generated by Django 4.2.30 on 2026-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xp_per_task",
                    models.IntegerField(
                        default=10, help_text="XP awarded for completing a task"
                    ),
                ),
                (
                    "free_projects_limit",
                    models.IntegerField(
                        default=3, help_text="Maximum number of free projects per user"
                    ),
                ),
                (
                    "anti_procrastination_threshold",
                    models.IntegerField(
                        default=3,
                        help_text="Hours of inactivity before anti-procrastination trigger",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("broadcast_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bot Settings",
            },
        ),
    ]
