# Generated by Django 4.2.30 on 2026-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("uk", "Ukrainian"), ("ru", "Russian")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_interaction_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
