# Generated by Django 4.2.30 on 2026-05-10 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_language_user_last_interaction_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
