# Generated by Django 4.2.30 on 2026-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_last_activity_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_goal",
            field=models.IntegerField(
                default=10800, help_text="Daily focus goal in seconds (default 3h)"
            ),
        ),
    ]
