# Generated by Django 4.2.30 on 2026-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar_url_user_daily_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="streak",
            field=models.IntegerField(default=0),
        ),
    ]
