# Generated by Django 4.2.13 on 2026-05-25 17:35

from django.db import migrations

def fix_timezone_names(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(timezone="Europe/Kiev").update(timezone="Europe/Kyiv")

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_streak"),
    ]

    operations = [
        migrations.RunPython(fix_timezone_names),
    ]
