# Generated by Django 4.2.30 on 2026-04-24 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('total_focus_time', models.IntegerField(default=0, help_text='Total focus time in seconds')),
                ('completed_tasks_count', models.IntegerField(default=0)),
                ('interruptions_count', models.IntegerField(default=0)),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Daily stats',
            },
        ),
    ]
