# Generated by Django 4.2.30 on 2026-04-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dailystats",
            name="analytics_d_user_id_418a05_idx",
        ),
    ]
