# Generated by Django 4.2.30 on 2026-04-24 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('focus_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'start_time'], name='focus_sessi_user_id_4a8f7c_idx'),
        ),
    ]
