# Generated by Django 4.2.30 on 2026-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus_sessions", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="last_paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="focussession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="target_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Target duration in seconds for countdown",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="total_paused_duration",
            field=models.IntegerField(
                default=0, help_text="Total paused duration in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="focussession",
            name="duration",
            field=models.IntegerField(
                default=0, help_text="Net focus duration in seconds"
            ),
        ),
    ]
