# Generated by Django 4.2.30 on 2026-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "focus_sessions",
            "0004_focussession_last_paused_at_focussession_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="focussession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
