# Generated by Django 4.2.30 on 2026-05-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="inactive_days_filter",
            field=models.IntegerField(
                blank=True,
                help_text="Send only to users inactive for more than X days",
                null=True,
            ),
        ),
    ]
